# fly.toml app configuration file generated for nutritious-foods on 2024-11-13T16:39:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nutritious-foods'
primary_region = 'otp'

[build]
  image = 'stefan107/nutritiousfoods:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
